version: "3.9"
services:
  mysql:
    container_name: mysql
    image: mysql:8
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: msvc_usuarios
    volumes:
      - F:\Curso_spring_cloud\data-mysql:/var/lib/mysql
    restart: always
    networks:
      - spring
  postgres14:
    container_name: postgres14
    image: postgres:14.2-alpine
    ports:
      - "5532:5432"
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: msvc_cursos
    volumes:
      - F:\Curso_spring_cloud\data-postgres:/var/lib/postgresql/data
    restart: always
    networks:
      - spring
  msvc-usuarios:
    container_name: msvc-usuarios
    build:
      context: .
      dockerfile: ./msvc-usuarios/Dockerfile
    ports:
      - "8001:8001"
    env_file: ./msvc-usuarios/.env
    networks:
      - spring
    depends_on:
      - mysql
    restart: always
  msvc-cursos:
    container_name: msvc-cursos
    build:
      context: .
      dockerfile: ./msvc-cursos/Dockerfile
    ports:
      - "8002:8002"
    env_file: ./msvc-cursos/.env
    networks:
      - spring
    depends_on:
      - postgres14
      - msvc-usuarios
    restart: always

networks:
  spring :
    name: spring
